package com.model;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class TDirector implements java.io.Serializable {

	// Fields

	private Integer userId;

	private String userName;

	private String userPw;
	
	private String userRealName;
	
	private String userTel;
	

	// Constructors

	/** default constructor */
	public TDirector() {
	}

	/** full constructor */
	public TDirector(String userName, String userPw) {
		this.userName = userName;
		this.userPw = userPw;
	}

	// Property accessors


	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return this.userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public Integer getUserId()
	{
		return userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getUserRealName() {
		return userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}

	public String getUserTel() {
		return userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

}